In [75]:
import torch
from scipy.optimize import linear_sum_assignment

In [22]:
out_box = torch.ones((100, 4))
out_box[:30] *= 5.
target_box = torch.ones((25, 4)) * 5.

In [23]:
out_box.shape

torch.Size([100, 4])

In [24]:
cost_bbox = torch.cdist(out_box, target_box, p=1)
cost_bbox.shape

torch.Size([100, 25])

In [25]:
out_cls = torch.randn((100, 2)).softmax(-1)
target_cls = torch.ones((25), dtype=torch.int)

In [26]:
cost_class = -out_cls[:, target_cls]
cost_class.shape

torch.Size([100, 25])

In [27]:
print(f"cost_box: {cost_bbox.shape}\ncost_class: {cost_class.shape}")

cost_box: torch.Size([100, 25])
cost_class: torch.Size([100, 25])


In [28]:
C = cost_class + cost_bbox

In [87]:
C = cost_class + cost_bbox
C = C.view(1, 100, -1)
C.shape

torch.Size([1, 100, 25])

In [80]:
len(C)

1

In [81]:
sizes = [1 for _ in range(25)]

In [82]:
c_splitted = C.split(sizes, -1)

In [83]:
c_splitted[0].shape

torch.Size([1, 100, 1])

In [90]:
linear_sum_assignment(C[0])

(array([ 1,  2,  3,  4,  5,  6,  7,  9, 11, 12, 13, 14, 16, 17, 18, 19, 21,
        22, 23, 24, 25, 26, 27, 28, 29]),
 array([10, 24, 21,  7, 14,  6, 15, 11,  5,  1, 17,  8, 13,  9, 16,  4, 20,
         0, 22, 12,  2,  3, 19, 18, 23]))

In [93]:
big_batch = torch.randn((1, 100, 25))
for i, c in enumerate(big_batch):
    print(f'{i} | {c.shape}')

0 | torch.Size([100, 25])


In [89]:
for i, c in enumerate(C.split(sizes, -1)):
    print(f'{i} | {c.shape}')
    #linear_sum_assignment(c[i])

0 | torch.Size([1, 100, 1])
1 | torch.Size([1, 100, 1])
2 | torch.Size([1, 100, 1])
3 | torch.Size([1, 100, 1])
4 | torch.Size([1, 100, 1])
5 | torch.Size([1, 100, 1])
6 | torch.Size([1, 100, 1])
7 | torch.Size([1, 100, 1])
8 | torch.Size([1, 100, 1])
9 | torch.Size([1, 100, 1])
10 | torch.Size([1, 100, 1])
11 | torch.Size([1, 100, 1])
12 | torch.Size([1, 100, 1])
13 | torch.Size([1, 100, 1])
14 | torch.Size([1, 100, 1])
15 | torch.Size([1, 100, 1])
16 | torch.Size([1, 100, 1])
17 | torch.Size([1, 100, 1])
18 | torch.Size([1, 100, 1])
19 | torch.Size([1, 100, 1])
20 | torch.Size([1, 100, 1])
21 | torch.Size([1, 100, 1])
22 | torch.Size([1, 100, 1])
23 | torch.Size([1, 100, 1])
24 | torch.Size([1, 100, 1])


In [76]:
linear_sum_assignment(c_splitted[0])

(array([22]), array([0]))

In [64]:
len(C.split(sizes, -1))

25

In [65]:
C.shape

torch.Size([1, 100, 25])

In [35]:
len(sizes)

100

In [38]:
a = torch.cat([torch.tensor([[1,2,3,4]]), torch.tensor([[1,2,3,4]])])

In [39]:
a.shape

torch.Size([2, 4])

In [77]:
indices = [linear_sum_assignment(c[i]) for i, c in enumerate(c_splitted)]
indices

ValueError: expected a matrix (2-D array), got a 1 array